services:
  atcoder:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
      args:
        USERNAME: vscode
        USER_UID: ${LOCAL_UID:-1000}
        USER_GID: ${LOCAL_GID:-1000}
        ATCODER_CLI_VERSION: 2.2.0
        ONLINE_JUDGE_TOOLS_VERSION: 11.5.1
        ACLOGIN_VERSION: 0.2.1
    init: true
    stdin_open: true
    tty: true
    working_dir: /workspace
    volumes:
      - .:/workspace
      - atcoder-cli-config:/home/vscode/.config/atcoder-cli-nodejs
      - online-judge-tools-data:/home/vscode/.local/share/online-judge-tools

volumes:
  atcoder-cli-config:
  online-judge-tools-data:
