services:
  atcoder:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile.prebuilt
      args:
        USER_UID: ${LOCAL_UID:-1000}
        USER_GID: ${LOCAL_GID:-1000}
    platform: linux/amd64
    init: true
    stdin_open: true
    tty: true
    working_dir: /workspace
    volumes:
      - .:/workspace
      - atcoder-cli-config:/home/vscode/.config/atcoder-cli-nodejs
      - online-judge-tools-data:/home/vscode/.local/share/online-judge-tools

volumes:
  atcoder-cli-config:
  online-judge-tools-data:
