FROM ghcr.io/foxy-null/atcoder-devcontainer-template@sha256:9d514740847fb5e4ffb23ce04d9771636539f3997559948ceb7165a1d9bb5f7e

# Compose does not perform Dev Containers' automatic UID/GID adjustment.
USER root
ARG USER_UID=1000
ARG USER_GID=1000
RUN if [ "$(id -g vscode)" != "${USER_GID}" ]; then groupmod --gid "${USER_GID}" vscode; fi \
    && if [ "$(id -u vscode)" != "${USER_UID}" ]; then usermod --uid "${USER_UID}" vscode; fi \
    && chown -R "${USER_UID}:${USER_GID}" /home/vscode
USER vscode
